name: Figma Design Submission
description: Submit a design file for review
title: '[Design]: '
labels: [design, figma, infraboard, xerocodee]
body:
  - type: markdown
    attributes:
      value: 'Thank you for submitting your design. Please provide the necessary details for review.'

  - type: input
    id: design-title
    attributes:
      label: Design Title
      description: 'What is the title of your design?'
      placeholder: 'Enter the title here'
    validations:
      required: true

  - type: textarea
    id: design-description
    attributes:
      label: Design Description
      description: 'Please provide a detailed description of your design.'
      placeholder: 'Describe your design here'
    validations:
      required: true

  - type: input
    id: figma-link
    attributes:
      label: Figma File Link
      description: 'Please paste the link to your Figma file.'
      placeholder: 'https://www.figma.com/file/...'
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: 'Please accept the terms and conditions.'
      options:
        - label: 'I have read and agree to the [Terms of Service](/terms) and [Privacy Policy](/privacy).'

  - type: dropdown
    id: design-category
    attributes:
      label: Design Category
      description: 'Please select the category your design best fits into.'
      options:
        - UI/UX
        - Branding
        - Icons
        - Illustrations
    validations:
      required: true
